apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-extent
  labels:
    account: extent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extent-v1
  labels:
    app: extent
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extent
      version: v1
  template:
    metadata:
      labels:
        app: extent
        version: v1
    spec:
      serviceAccountName: sa-extent
      containers:
      - name: extent
        image: sousaha/extent:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
---