apiVersion: v1
kind: Service
metadata:
  name: extent
  labels:
    app: extent
    version: v1
spec:
  selector:
    app: extent
    version: v1
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  
    
  